/**
 * Proxy vocabulary — shared by the wizard, the API routes and the engine.
 *
 * The rule this module exists to enforce:
 *
 * **A saved job describes *where* its traffic should leave from, never *how* to
 * authenticate.** `fetch.proxy` therefore holds one of three things:
 *
 * | Value                        | Meaning                                          |
 * | ---------------------------- | ------------------------------------------------ |
 * | `null`                       | Direct connection (or the server's static pool).  |
 * | `decodo` / `decodo://?…`     | Managed residential, credentials from the engine. |
 * | `http://user:pass@host:port` | An explicit proxy. Credentials end up in the job. |
 *
 * The third form is supported because self-hosted proxies are legitimate, but
 * the wizard steers users to the second one for exactly the reason it is
 * listed second: a job config is read back by the API, rendered in the UI,
 * exported to JSON and copied into bug reports. Nothing secret belongs in it.
 *
 * The string is deliberately *not* a URL with a scheme per provider: the engine
 * is the only component that knows which providers exist and what a credential
 * means, so the client stays a dumb builder of a documented string.
 */

export const PROXY_KINDS = ['direct', 'decodo', 'custom'] as const;
export type ProxyKind = (typeof PROXY_KINDS)[number];

/** The literal a job stores when it wants the engine's default proxy. */
export const DECODO_PROXY_VALUE = 'decodo';

export interface ProxySelection {
  kind: ProxyKind;
  /** ISO-3166 alpha-2, or null for the account default. */
  country?: string | null;
  city?: string | null;
  /** Sticky-session id. Generated by the wizard when sticky is enabled. */
  session?: string | null;
  /** Sticky-session lifetime in minutes (Decodo allows 1–1440). */
  stickyMinutes?: number | null;
  /** Only for `kind: 'custom'`. */
  customUrl?: string | null;
}

/**
 * A shortlist, not the full ISO list: Decodo's dashboard offers ~200 countries
 * and a `<select>` that long is a worse experience than typing. The engine
 * accepts any valid code, so an API user can target one that is not listed.
 */
export const DECODO_COUNTRIES: Array<{ code: string; label: string }> = [
  { code: 'us', label: 'United States' },
  { code: 'ca', label: 'Canada' },
  { code: 'gb', label: 'United Kingdom' },
  { code: 'ie', label: 'Ireland' },
  { code: 'de', label: 'Germany' },
  { code: 'fr', label: 'France' },
  { code: 'nl', label: 'Netherlands' },
  { code: 'es', label: 'Spain' },
  { code: 'it', label: 'Italy' },
  { code: 'se', label: 'Sweden' },
  { code: 'pl', label: 'Poland' },
  { code: 'br', label: 'Brazil' },
  { code: 'mx', label: 'Mexico' },
  { code: 'in', label: 'India' },
  { code: 'jp', label: 'Japan' },
  { code: 'sg', label: 'Singapore' },
  { code: 'au', label: 'Australia' },
];

export const DECODO_STICKY_MINUTES: number[] = [1, 5, 10, 30, 60, 180];

export const PROXY_HELP: Record<ProxyKind, string> = {
  direct:
    'Requests leave from this server’s own address. Cheapest and fastest; use it unless a site blocks you.',
  decodo:
    'Residential addresses from Decodo. The credential lives in the engine’s environment, so the job itself stays secret-free. Choose a country when the site is geo-specific.',
  custom:
    'Any HTTP/HTTPS/SOCKS5 proxy you run yourself. The URL is stored with the job — including any credentials in it.',
};

/**
 * Turn a selection into the string a job stores.
 *
 * Empty selection and a direct connection both produce `null`, because "the
 * default" and "no proxy" must not be two different states in the database.
 */
export function buildProxyValue(selection: ProxySelection): string | null {
  if (selection.kind === 'direct') return null;

  if (selection.kind === 'custom') {
    const url = selection.customUrl?.trim();
    return url && url.length > 0 ? url : null;
  }

  const params = new URLSearchParams();
  if (selection.country) params.set('country', selection.country.toLowerCase());
  if (selection.city) params.set('city', selection.city.trim().toLowerCase().replace(/\s+/g, '_'));
  if (selection.session) params.set('session', selection.session);
  if (selection.stickyMinutes) {
    params.set('sticky', String(Math.min(1440, Math.max(1, Math.round(selection.stickyMinutes)))));
  }

  const query = params.toString();
  return query ? `decodo://?${query}` : DECODO_PROXY_VALUE;
}

/** Read a stored value back into the form, so editing a job is not lossy. */
export function parseProxyValue(value: string | null | undefined): ProxySelection {
  if (!value || value.trim().length === 0) return { kind: 'direct' };

  const raw = value.trim();
  if (!raw.toLowerCase().startsWith('decodo')) return { kind: 'custom', customUrl: raw };

  const query = raw.slice('decodo'.length).replace(/^[:/]*/, '').replace(/^\?/, '');
  if (!query) return { kind: 'decodo' };

  try {
    const params = new URLSearchParams(query);
    const sticky = Number(params.get('sticky'));
    return {
      kind: 'decodo',
      country: params.get('country'),
      city: params.get('city'),
      session: params.get('session'),
      stickyMinutes: Number.isFinite(sticky) && sticky > 0 ? sticky : null,
    };
  } catch {
    return { kind: 'decodo' };
  }
}

export interface ProxyDescription {
  kind: ProxyKind;
  /** Short badge text. */
  label: string;
  /** One sentence of context for a tooltip or a details row. */
  detail: string;
  /** True when the stored value may contain a credential. */
  carriesCredentials: boolean;
}

/**
 * Describe a stored value for display.
 *
 * Never returns the credential part of a custom proxy URL — this output is
 * rendered in the UI and copied into support tickets.
 */
export function describeProxy(value: string | null | undefined): ProxyDescription {
  if (!value || value.trim().length === 0) {
    return {
      kind: 'direct',
      label: 'Direct',
      detail: 'Traffic leaves from the engine’s own IP address.',
      carriesCredentials: false,
    };
  }

  const raw = value.trim();
  if (!raw.toLowerCase().startsWith('decodo')) {
    return {
      kind: 'custom',
      label: 'Custom proxy',
      detail: `Traffic leaves through ${safeHost(raw)}.`,
      carriesCredentials: raw.includes('@'),
    };
  }

  const parsed = parseProxyValue(raw);
  const bits: string[] = [];
  if (parsed.country) {
    bits.push(DECODO_COUNTRIES.find((entry) => entry.code === parsed.country)?.label ?? parsed.country.toUpperCase());
  }
  if (parsed.city) bits.push(titleCase(parsed.city.replace(/_/g, ' ')));

  const mode = parsed.session
    ? `sticky IP for ${parsed.stickyMinutes ?? 10} min`
    : 'rotating IP';

  return {
    kind: 'decodo',
    label: bits.length > 0 ? `Decodo · ${bits.join(' · ')}` : 'Decodo',
    detail: `Residential addresses from Decodo, ${mode}. Credentials come from the engine’s environment.`,
    carriesCredentials: false,
  };
}

/** True when a job needs Decodo credentials to be configured server-side. */
export function usesDecodo(value: string | null | undefined): boolean {
  return Boolean(value && value.trim().toLowerCase().startsWith('decodo'));
}

/** A sticky-session id. Short, URL-safe, and unique per job run. */
export function newProxySessionId(): string {
  const cryptoApi = globalThis.crypto;
  if (cryptoApi && typeof cryptoApi.randomUUID === 'function') {
    return `ws${cryptoApi.randomUUID().replace(/-/g, '').slice(0, 12)}`;
  }
  return `ws${Math.random().toString(36).slice(2, 14)}`;
}

// ---------------------------------------------------------------------------
function titleCase(input: string): string {
  return input.replace(/\b[a-z]/g, (character) => character.toUpperCase());
}

function safeHost(url: string): string {
  try {
    return new URL(url).host || 'a proxy';
  } catch {
    return 'a proxy';
  }
}
